#!/usr/bin/env python3
"""
Test to see what YAML parser produces from the action file.
"""

import yaml

def test_yaml_parsing():
    content = '''type: email_send
to: "Hooriya M.Fareed" <guujarmahnoor0312@gmail.com>
subject: Re: URGENT: Final Project Requirements & Approval
body: This is an automated reply generated by the AI Employee. We
received your urgent message.'''

    print("Testing YAML parsing of action file content...")
    print(f"Content:\n{content}\n")
    
    try:
        parsed = yaml.safe_load(content)
        print("YAML parsed result:")
        for key, value in parsed.items():
            print(f"  {key}: {repr(value)}")
    except yaml.YAMLError as e:
        print(f"YAML parsing failed: {e}")

if __name__ == "__main__":
    test_yaml_parsing()